import { ChakraUIProvider } from "@/providers/ChakraUIProvider";
import type { Metadata } from "next";
import { Inter, KoHo } from "next/font/google";
import "./globals.css";
import TanstackProvider from "@/providers/TanstackProvider";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter"});
const koHo = KoHo({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
  variable: "--font-koho",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${koHo.variable}`}>
        <ChakraUIProvider>
          <TanstackProvider>{children}</TanstackProvider>
        </ChakraUIProvider>
      </body>
    </html >
  );
}
